/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Context } from "./Context";
export type { ERC20 } from "./ERC20";
export type { IERC20 } from "./IERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { TokenSample } from "./TokenSample";
export type { ZennCoin } from "./ZennCoin";
